# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/radesh/Documentos/signinc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/radesh/Documentos/signinc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/radesh/Documentos/signinc/CMakeFiles /home/radesh/Documentos/signinc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/radesh/Documentos/signinc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_signinC

# Build rule for target.
test_signinC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_signinC
.PHONY : test_signinC

# fast build rule for target.
test_signinC/fast:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/build
.PHONY : test_signinC/fast

#=============================================================================
# Target rules for targets named SignInC

# Build rule for target.
SignInC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SignInC
.PHONY : SignInC

# fast build rule for target.
SignInC/fast:
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/build
.PHONY : SignInC/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/signer.o: src/signer.cpp.o

.PHONY : src/signer.o

# target to build an object file
src/signer.cpp.o:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/src/signer.cpp.o
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/src/signer.cpp.o
.PHONY : src/signer.cpp.o

src/signer.i: src/signer.cpp.i

.PHONY : src/signer.i

# target to preprocess a source file
src/signer.cpp.i:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/src/signer.cpp.i
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/src/signer.cpp.i
.PHONY : src/signer.cpp.i

src/signer.s: src/signer.cpp.s

.PHONY : src/signer.s

# target to generate assembly for a file
src/signer.cpp.s:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/src/signer.cpp.s
	$(MAKE) -f CMakeFiles/SignInC.dir/build.make CMakeFiles/SignInC.dir/src/signer.cpp.s
.PHONY : src/signer.cpp.s

tests/test_signinC.o: tests/test_signinC.cpp.o

.PHONY : tests/test_signinC.o

# target to build an object file
tests/test_signinC.cpp.o:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/tests/test_signinC.cpp.o
.PHONY : tests/test_signinC.cpp.o

tests/test_signinC.i: tests/test_signinC.cpp.i

.PHONY : tests/test_signinC.i

# target to preprocess a source file
tests/test_signinC.cpp.i:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/tests/test_signinC.cpp.i
.PHONY : tests/test_signinC.cpp.i

tests/test_signinC.s: tests/test_signinC.cpp.s

.PHONY : tests/test_signinC.s

# target to generate assembly for a file
tests/test_signinC.cpp.s:
	$(MAKE) -f CMakeFiles/test_signinC.dir/build.make CMakeFiles/test_signinC.dir/tests/test_signinC.cpp.s
.PHONY : tests/test_signinC.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... test_signinC"
	@echo "... SignInC"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/signer.o"
	@echo "... src/signer.i"
	@echo "... src/signer.s"
	@echo "... tests/test_signinC.o"
	@echo "... tests/test_signinC.i"
	@echo "... tests/test_signinC.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

